language: php 
php: 
 - 5.3
 - 5.4

sudo: false

env:
 - DB=MYSQL CORE_RELEASE=3.0
 - DB=MYSQL CORE_RELEASE=3
 - DB=PGSQL CORE_RELEASE=3
 - DB=SQLITE CORE_RELEASE=3

matrix:
  exclude:
    - php: 5.4
      env: DB=PGSQL CORE_RELEASE=3
    - php: 5.4
      env: DB=SQLITE CORE_RELEASE=3
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.0

before_script:
 - pear -q install --onlyreqdeps pear/PHP_CodeSniffer
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - phpunit restfulserver/tests/
 - phpcs --encoding=utf-8 --tab-width=4 --standard=restfulserver/tests/phpcs -np restfulserver
